"""Add Phase 7 share_token rating feedback columns

Revision ID: edf00e3983f3
Revises: bf22749c6ab4
Create Date: 2026-09-14 08:33:27.465169

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'edf00e3983f3'
down_revision: str | Sequence[str] | None = 'bf22749c6ab4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generated_resumes', sa.Column('share_token', sa.String(), nullable=True))
    op.add_column('generated_resumes', sa.Column('rating', sa.Integer(), nullable=True))
    op.add_column('generated_resumes', sa.Column('feedback_text', sa.Text(), nullable=True))
    op.create_index(op.f('ix_generated_resumes_share_token'), 'generated_resumes', ['share_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generated_resumes_share_token'), table_name='generated_resumes')
    op.drop_column('generated_resumes', 'feedback_text')
    op.drop_column('generated_resumes', 'rating')
    op.drop_column('generated_resumes', 'share_token')
    # ### end Alembic commands ###
